### ISSUE TITLE
java.lang.NullPointerException crash in Android WebView

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-webview#1406]
**Bug description:**
Hello, upon looking at app crashes in google play console, 
I am getting following crash log from the users: 

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: 
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:98)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:134)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:54)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:48)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:278)
  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:179)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:773)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:888)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2200 (UIViewOperationQueue.java:42)
  at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded (UIViewOperationQueue.java:846)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:29)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:227)
  at android.app.ActivityThread.main (ActivityThread.java:7212)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:575)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:887)

Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:83)

Caused by: java.lang.NullPointerException: 
  at com.reactnativecommunity.webview.RNCWebViewManager.setupWebChromeClient (RNCWebViewManager.java:652)
  at com.reactnativecommunity.webview.RNCWebViewManager.setAllowsFullscreenVideo (RNCWebViewManager.java:519)
  at .CPU
  at .29
  at .27
  at .14
  at .10
  at .10
  at 8.5
  at 5.8
  at .5
  at 3.5
  at 4.5
  at 4.3
  at .4
  at 2.8
  at 2.6
  at 1.3
  at 1.7
  at 1.7
  at 1.2
  at 1.4
  at 1.3
  at 0.3
  at 1.2
  at 1.1
  at .1
  at .1
```

seems to be caused by react native webview. 

**Environment:**
 - OS: MacOS
 - OS version: 10.15.4
 - react-native version: 0.61.5
 - react-native-webview version: 9.4.0

**Comment by akread** [comment]
Has anyone else seen this bug? I am getting reports of the same crash in my app.

```
Error while updating property 'allowsFullscreenVideo' of a view managed by: RNCWebView
```

```
java.lang.NullPointerException
Attempt to invoke virtual method 'int android.app.Activity.getRequestedOrientation()' on a null object reference
```

https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L674 appears to be the source of the issue - calling `getRequestedOrientation()` on a `null` activity.

react-native version: 0.62.2
react-native-webview version: 8.1.2

I know there are newer versions of react-native-web-view but that code there doesn't seem to have really changed.

Can we re-open this ticket?

**Comment by Bang9** [comment]
@akread +1

**Comment by JakeStoeffler** [comment]
+1 to re-opening the issue.
Confirmed this issue still exists in react-native-webview 10.9.3 with react-native 0.63.3

**Comment by jdgalani** [comment]
+1 for reopening

**Comment by jdgalani** [comment]
> +1 to re-opening the issue.
> Confirmed this issue still exists in react-native-webview 10.9.3 with react-native 0.63.3
> 
> I was able to use [patch-package](https://www.npmjs.com/package/patch-package) to work around it:
> 
> ```
> diff --git a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
> index e042a50..0ada70a 100644
> --- a/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
> +++ b/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java
> @@ -566,6 +566,7 @@ public class RNCWebViewManager extends SimpleViewManager<WebView> {
>      WebView view,
>      @Nullable Boolean allowsFullscreenVideo) {
>      mAllowsFullscreenVideo = allowsFullscreenVideo != null && allowsFullscreenVideo;
> +    if (((ReactContext)view.getContext()).getCurrentActivity() == null) mAllowsFullscreenVideo = false;
>      setupWebChromeClient((ReactContext)view.getContext(), view);
>    }
> ```
> 
> Unfortunately it means fullscreen video may not always be available in Android, but for our use case, it's better than the app crashing.

what if I pass
```
webViewProps={{
   allowsFullscreenVideo: false,
}}
```

would it be resolved?
FYI: I can't test it, because all the devices I have are working fine, but getting crash reports in crashlytics.

**Comment by vectorwing** [comment]
We're also facing this issue on our current project; though we were unable to test locally, users are suffering crashes from it. I'd also like for it to be reopened.

**Comment by TfADrama** [comment]
Does anybody knows if this was fixed on newer versions?

**Comment by philpettican** [comment]
Seeing this error pretty much everyday in the google store console. Looking at the file history, it doesn't look like this has been fixed in the latest version. Can this please be reopened?

`com.facebook.react.bridge.JSApplicationIllegalArgumentException: 
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:102)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:136)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:56)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:49)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:270)
  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:186)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:911)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
  at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded (UIViewOperationQueue.java:986)
  at com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:31)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
 Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:87)
 Caused by: java.lang.NullPointerException: 
  at com.reactnativecommunity.webview.RNCWebViewManager.setupWebChromeClient (RNCWebViewManager.java:712)
  at com.reactnativecommunity.webview.RNCWebViewManager.setAllowsFullscreenVideo (RNCWebViewManager.java:576)`

Environment:
OS: MacOS
OS version: 10.15.7
react-native version: 0.63.3
react-native-webview version: 11.0.2

**Comment by antonrifco** [comment]
+1 issue still exist

**Comment by smathson** [comment]
Still happening for us too. This issue should be re-opened.

react-native 0.64.1
react-native-webview 11.4.4
