### ISSUE TITLE
scrollEnabled false on Android

### ISSUE THREAD

**Issue by Madnarth** [react-native-community/react-native-webview#1490]
**Bug description:**

Can't disable scrolling (vertically) in WebView component. I have a WebView component with a simple HTML source within containing only text.

I'm using Expo.
**To Reproduce:**

```js
<WebView
  scrollEnabled={false}
  source={{ html: `
    <div>
      Some very long text here
    </div>
  ` }}
/>
```
**Expected behavior:**

I want to disable scroll as I would with ScrollView for example, but prop `scrollEnabled` set to false is not working for me. I tried to disable scrolling inside HTML with `style="height: 100%; overflow: hidden;"` but this not working either.
**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 9.0 - API 28
 - react-native version: sdk-37
 - react-native-webview version: 10.3.2

**Comment by mik-rom** [comment]
I have the same issue

**Comment by sorakrisc** [comment]
from the document https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#scrollenabled scroll enabled props is only for ios and macos

it used to work on android as well

**Comment by sparsh-jj** [comment]
Any Idea when it use to work, I am working on drag and drop application and I am unable to stop scroll on webview in Android.

It is working perfectly is iOS though

**Comment by vivek-bluebash** [comment]
Same issue with an additional bug, I have many webviews on the screen which I'm not able to scroll currently, that's good but I still can see the scroll.

**Comment by vivek-bluebash** [comment]
The issue in my case where I just wanted to disable the vertical scroll is solved using other prop named `showsVerticalScrollIndicator` which just hides the vertical indicator.

**Comment by SantyLorenzo** [comment]
I am having the same issue.

**Comment by JerakRus** [comment]
Why was the problem closed? It still doesn't work. Needed for use inside ScrollView.
Props nestedScrollEnabled, according to the description, turns off the scrolling of the top ScrollView, but I just need the opposite to use refreshControl

**Comment by EmilianoMorghen** [comment]
2022 here. Still not working on Android.

**Comment by hke-ghtest2** [comment]
2023 here. Still not working on Android.

**Comment by GzhiYi** [comment]
2023-08. Still not working on Android.Should this issue be reopened?

**Comment by mdarahman** [comment]
2023-10 still the same issue persists

**Comment by mdarahman** [comment]
use the prop overScrollMode={'never'}, it worked for me

**Comment by arunava-adrobit** [comment]
Still not working on 19-01-2024.

**Comment by CarlMenke** [comment]
We need this for android please

**Comment by shivam0831** [comment]
any updates on this issue?

**Comment by jasontlouro** [comment]
🥲

**Comment by 0xIrakli** [comment]
still the same issue using expo. sep 2024

**Comment by johnsonfash** [comment]
Same isssue Oct 20, 2024.

**Comment by kiet-ap** [comment]
Noway

**Comment by chandlery54** [comment]
Still a problem in Dec. 2025 on `6.9.1` for Expo Go. Hopefully resolved in later versions.
