### ISSUE TITLE
Android needs full screen video support

### ISSUE THREAD

**Issue by smathson** [react-native-community/react-native-webview#294]
Currently videos playing inline on Android cannot be opened fullscreen. This issue was brought up in #172 which is an unrelated bug, although it might be a good alternative to a fix for that issue if we can’t figure out the underlying cause.

This needs to be implemented in a similar way to these projects:
https://github.com/teamairship/react-native-android-fullscreen-webview-video
https://github.com/haozes/react-native-webview-file-upload-android

I’ll need to do this for our app in the coming month but if anyone else wants to take a crack at it in the meantime it would probably be a good candidate for a first issue.

**Comment by Titozzz** [comment]
#265 Might be related?

**Comment by drbarto** [comment]
The "good first issue" label looks inviting to me ;-) but I'm not an Android dev, so any hint where to start with fixing this issue would be appreciated.

**Comment by benhartouz** [comment]
I have the same issue here, I can't go fullscreen.

**Comment by smathson** [comment]
@drbarto Sorry, missed your message. Check out the linked PR above, looks like we're close to having this issue resolved.

@benhartouz Keep an eye on when #325 lands. It adds fullscreen video support on Android.

**Comment by Albert0405** [comment]
Please do update us when it's done. Thanks

**Comment by benhartouz** [comment]
@smathson I have this #325 merge to the master soon.

**Comment by Titozzz** [comment]
Hello there was some issues with 5.9.0, 6.0.0 and 6.O.1

I fixed 6.0.2 and also released 5.9.1 if you don't want to upgrade!

**Comment by emomooney** [comment]
Is this working? I've updated to 5.11.0, still doesn't seem to work for Android fullscreen video.

**Comment by dmsierra11** [comment]
@emomooney did you manage to make it work? It doesn't work for me either with version 5.9.1

**Comment by emomooney** [comment]
emm... I honestly can't remember what the original issue was. But I ended up using a module : [react-native-android-fullscreen-webview-video](https://www.npmjs.com/package/react-native-android-fullscreen-webview-video) 
`
import WebView from 'react-native-android-fullscreen-webview-video';
import wistiaWebView from './WistiaWebView';
...  
<WebView
    source={{
              html: wistiaWebView(this.props.challenge.item.content.video)
            }}
            originWhitelist={['*']}
     />
`

Example of WistaWebView
`export default videoId =>
    `<!DOCTYPE html>
    <html style="height: 100%; width: 100%; padding: 0; margin:0;">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <style>
          html,
          body {
            overflow-x: hidden;
            overflow-y: hidden;
            padding: 0;
            margin: 0;
          }
          body {
            position: relative;
            padding: 0;
            margin: 0;
            background-color: black;
          }
        </style>
      </head>
      <body>
        <script
          src="https://fast.wistia.com/embed/medias/${videoId}.jsonp"
          async
        ></script>
        <script
          src="https://fast.wistia.com/assets/external/E-v1.js"
          async
        ></script>
        <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;">
        <div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;">
        <div class="wistia_embed wistia_async_${videoId} seo=false videoFoam=true controlsVisibleOnLoad=false fullscreenButton=true allowfullscreen=true settingsControl=false smallPlayButton=false" style="height:100%;width:100%">&nbsp;</div></div></div>
      </body>
    </html>
    `;
`

Works ok for me on android and ios, but I have a feeling it needs to be worked on style wise for different devices.

**Comment by motogod** [comment]
I have upgraded `react-native-webview` version to 5.12.1

It still doesn't work for me.

```
import { WebView } from 'react-native-webview';

    return (
      <View style={{ width, height: 240 }}>
        <WebView
          mediaPlaybackRequiresUserAction={true}
          source={{ uri: `https://www.youtube.com/embed/${videoId}?rel=0` }}
        />
      </View>
    );
```

I can not click the zoom icon that is still transparent.

<img width="242" alt="螢幕快照 2019-07-19 下午3 19 19" src="https://user-images.githubusercontent.com/17781603/61517200-45a7e680-aa39-11e9-9c5b-b2a792b38c32.png">

**Comment by lpikora** [comment]
@motogod 
There is a new Android only `allowsFullscreenVideo` property of <WebView>. It defaults to false, so just set it true and fullscreen should work on Android. 

`<WebView allowsFullscreenVideo={true} ...`

https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#allowsfullscreenvideo

**Comment by IlyassElharrar** [comment]
@lpikora the easiest way to do it !! thanks
