### ISSUE TITLE
Not able to compile or build apk with Android

### ISSUE THREAD

**Issue by codoffer** [react-native-community/react-native-webview#581]
I am facing this issue with Android only.

When I am trying from Android studio. Its generating apk AVD but not working with command. Getting below error

**To Reproduce:**
RUN with react-native run-android OR ./gradlew app:assembleDebug

**Expected behavior:**

**Screenshots/Videos:**

> Task :react-native-webview:compileDebugJavaWithJavac FAILED
/Projects/codoffer-hero/codofferhero/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:14: error: cannot find symbol
import androidx.annotation.RequiresApi;
                          ^
  symbol:   class RequiresApi
  location: package androidx.annotation
/Projects/codoffer-hero/codofferhero/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:15: error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;

**Environment:**
 - OS: Mac
 - OS version:
 - react-native version: 0.59.1
 - react-native-webview version: ^6.0.1

**Comment by laf1greg** [comment]
I have a similar problem (not sure if it's the same problem). 

**Tried with:**
- react-native version: 0.59.8
- react-native-webview version: ^6.0.1

> react-native run-android
> info JS server already running.
> info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...
> 
> > Configure project :react-native-webview
> :react-native-webview:reactNativeAndroidRoot /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native/android
> 
> > Task :react-native-webview:compileDebugJavaWithJavac FAILED
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java:3: error: package androidx.core.content does not exist
> import androidx.core.content.FileProvider;
>                             ^
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewFileProvider.java:10: error: cannot find symbol
> public class RNCWebViewFileProvider extends FileProvider {
>                                             ^
>   symbol: class FileProvider
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:14: error: cannot find symbol
> import androidx.annotation.RequiresApi;
>                           ^
>   symbol:   class RequiresApi
>   location: package androidx.annotation
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:15: error: package androidx.core.content does not exist
> import androidx.core.content.ContextCompat;
>                             ^
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:16: error: package androidx.core.content does not exist
> import androidx.core.content.FileProvider;
>                             ^
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:178: error: cannot find symbol
>   @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
>    ^
>   symbol:   class RequiresApi
>   location: class RNCWebViewModule
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:224: error: cannot find symbol
>     if (ContextCompat.checkSelfPermission(getCurrentActivity(), Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
>         ^
>   symbol:   variable ContextCompat
>   location: class RNCWebViewModule
> /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:352: error: cannot find symbol
>     return FileProvider.getUriForFile(getReactApplicationContext(), packageName + ".fileprovider", capturedFile);
>            ^
>   symbol:   variable FileProvider
>   location: class RNCWebViewModule
> Note: /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /home/gregoire/code/rn2-igetwind/iGetwind/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 8 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 16 actionable tasks: 3 executed, 13 up-to-date
> error Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html
> error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.

**Comment by codoffer** [comment]
I have downgraded the version but it's creating crash with ios.

**Comment by Slowl** [comment]
I'm having the same error as you, I've been following the resolution of this issue #325 for a few weeks  so I tried to upgrade react-native-webview but now I can't build my app anymore, even with an older version 

Tried on : 
Ubuntu 19.04
React-Native 0.59.1
React-Native-Webview 6.0.1

**Comment by LorandP** [comment]
The project does build by installing from that repository but how do you import the webview? It doesn't work like `import WebView from 'react-native-webview'`

**Comment by dvicory** [comment]
> The project does build by installing from that repository but how do you import the webview? It doesn't work like `import WebView from 'react-native-webview'`

You need to import using `import { WebView } from 'react-native-webview'`.

> I installed React-Native-Webview from a branch that @dvicory made and shared here
Then I removed "import com.airship.customwebview.CustomWebViewPackage;" and "new CustomWebViewPackage()," from android > app > src > main > java > com > yourapp > MainApplication.java and now my app can run.
> 
> BUT no still no fullscreen for me, tested on a OnePlus One with Android 9.0.

You need to set the `allowsFullscreenVideo` prop to `true`, as by default it is off due to some people in #325 experiencing issues on some devices.

`react-native-webview` 6.x won't work for most people as it switched to AndroidX, which will require some configuration changes (and may not even work until react-native 0.60 is released). 5.9.0 should work, but I'd need to try it myself...

**Comment by dvicory** [comment]
Just verified 5.9.0 doesn't work. #577 was made and released as 6.0.1, but 6.0.0 comes with its own breaking changes. Perhaps we can get a 5.9.1 release with this fix.

**Comment by Titozzz** [comment]
@LorandP both named and default import are supported so youre issue lies somewhere else
@Slowl @codoffer @laf1greg can you show me your build.gradle files ?

**Comment by Titozzz** [comment]
@dvicory as said in the other thread do you have a reason to use custom buidtools that would make 6.0 not usable for you ?

**Comment by dankobaia** [comment]
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-webview": "5.8.0"
  }

working here

**Comment by Titozzz** [comment]
Hello I fixed 6.0.2 and also released 5.9.1 if you don't want to upgrade!

**Comment by Josephdias92** [comment]
> Hello I fixed 6.0.2 and also released 5.9.1 if you don't want to upgrade!

Hello @Titozzz I see that 6.0.2 has been released but 5.9.1 is still not released.

**Comment by Titozzz** [comment]
It is on npm just not visible on GitHub sorry for the inconvenience

**Comment by laf1greg** [comment]
Maybe there is something I didn't get but I have this error when I upgraded to 5.9.1 (or 5.8.0). It work with 5.2.0.

"react": "16.8.3",
"react-native": "0.59.8",
"react-native-webview": "5.9.1"

![Screenshot_2019-05-22-08-39-07-537_com igetwind](https://user-images.githubusercontent.com/3586754/58175238-b61acd00-7c6d-11e9-8cf7-5a43b60ad644.png)

**Comment by gentle-shao** [comment]
Hi,I solved this so here's my solution
* Create another new React-Native project
* Install **latest** react-native-webview
* **npm install --save react-native-webview@6.3.1**
* LINKING
* **react-native link react-native-webview**
* Run your project
* **react-native run-android**
* Edit *App.js* to this

import React, { Component } from 'react';
import { WebView } from 'react-native-webview';

```
export default class MyWeb extends Component {
  render() {
    return (
      <WebView
        source={{ uri: 'https://infinite.red' }}
        style={{ marginTop: 20 }}
      />
    );
  }
}
```

Good luck.

**Comment by dhivyada1** [comment]
"react-native-webview": "5.8.0" works perfectly. Thank you

**Comment by strdr4605** [comment]
@Titozzz, having this issue with:
OS: Mac
```json
"react-native": "0.59.9",
"react-native-webview": "7.4.3",
```
